
[functions.stripe-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/stripe-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-webhook/*.html" ]

[functions.auto-emailer]
enabled = true
verify_jwt = false
import_map = "./functions/auto-emailer/deno.json"
entrypoint = "./functions/auto-emailer/index.ts"

[functions.resend-sync]
enabled = true
verify_jwt = true
import_map = "./functions/resend-sync/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/resend-sync/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/resend-sync/*.html" ]

[functions.send-portal-access]
enabled = true
verify_jwt = true
import_map = "./functions/send-portal-access/deno.json"
entrypoint = "./functions/send-portal-access/index.ts"

[functions.send-booking-confirmation]
enabled = true
verify_jwt = false
import_map = "./functions/send-booking-confirmation/deno.json"
entrypoint = "./functions/send-booking-confirmation/index.ts"

[functions.create-booking-checkout]
enabled = true
verify_jwt = false
import_map = "./functions/create-booking-checkout/deno.json"
entrypoint = "./functions/create-booking-checkout/index.ts"

[functions.resend-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/resend-webhook/deno.json"
entrypoint = "./functions/resend-webhook/index.ts"
